### ISSUE TITLE
tools

### ISSUE THREAD

**Issue by h-oll** [suhr/nur-packages#31]
Hi @suhr 

thanks for putting up your personal nur on github. I was interested in having a droidcam derivation which brought me here. I'm however very new to nix. Would you mind explaining where the structure of your nur comes from (is that coming from some automated tool, or did you design it). 

Cheers.

**Comment by suhr** [comment]
There's a repository template: https://github.com/nix-community/nur-packages-template.

**Comment by h-oll** [comment]
> There's a repository template: https://github.com/nix-community/nur-packages-template.

Thks for your answer. I had missed that! Cheers.

>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.
>

-- 
Harold OLLIVIER
+33 617 103 898
