### ISSUE TITLE
v4l2loopback-dc not working?

### ISSUE THREAD

**Issue by gatlee** [suhr/nur-packages#33]
Hi, just would like to say thanks for putting in the effort to package all of this!

I'm not sure if it's because of my own incompetence but I've tried installing your v4l2loopback-dc and your droidcam package and whenever I start droidcam it still says 

```
Droidcam video device not found
Did it install correctly?
If you had a kernel update, you may need to re-install
```
I have it installed like this

```
{
  environment.systemPackages = with pkgs; [
    nur.repos.suhr.droidcam
    nur.repos.suhr.v4l2loopback-dc
  ]
}
```

If you could show me how you get it working on your system it would be greatly appreciated!

Thanks :)

**Comment by suhr** [comment]
Kernel modules are installed in a different way in NixOS. Basically, you need something like this in your configuration file:

```nix
{
  boot.extraModulePackages = [
    pkgs.nur.repos.suhr.v4l2loopback-dc
  ];
  boot.kernelModules = [
    "v4l2loopback-dc"
  ];
}
```

**Comment by gatlee** [comment]
Ahh that's what I was missing. Thanks so much for the help!
