### ISSUE TITLE
Bump droidcam to v1.6

### ISSUE THREAD

**Issue by fufexan** [suhr/nur-packages#39]
This way it can use the default `v4l2loopback` and doesn't need the `-dc` anymore.

**Comment by suhr** [comment]
Oh, it now supports the ordinary `v4l2loopback`? I guess, it's time to make a PR to nixpkgs.

**Comment by fufexan** [comment]
Great idea!
I've spent my entire night getting it to work. Probably would have given up, were it not for this awesome work of yours. There sure are other, more inexperienced users who probably did give up, and having droidcam in nixpkgs would be great for them (and anyone who needs it).

**Comment by suhr** [comment]
cc @jtojnar

**Comment by collares** [comment]
Would be great to have this in nixpkgs! Is there any way I can help?

**Comment by suhr** [comment]
> Is there any way I can help?

Someone needs to update the derivation and create a PR to nixpkgs.

**Comment by fufexan** [comment]
I'm trying to build the derivation but I'm getting `error: infinite recursion encountered, at undefined position`.

Here's the derivation: https://pastebin.com/gRVsVaPq

**Comment by suhr** [comment]
Actually, after changing the hash to `sha256-3RmEmLNUbwIh+yr7vtYZnMwbzfmtW3mz5u4Ohau9OLU=` I could build your derivation successfully.

Would you like to create a PR to nixpkgs?

**Comment by fufexan** [comment]
I would like to, yeah.

**Comment by suhr** [comment]
I created a draft of the PR: https://github.com/NixOS/nixpkgs/pull/108346.

To build it, you can do the following:

1. `git clone https://github.com/suhr/nixpkgs.git ; cd nixpkgs`
2. `git switch droidcam`
3. `nix-build -A droidcam`

I tried to build it and got the following error:

```
error: --- Error ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------ nix-build
builder for '/nix/store/rg40j3i3rzl69n7rl8xaiihsrlkw60d9-droidcam-1.6.drv' failed with exit code 2; last 10 log lines:
  src/usb.c: In function 'int CheckAdbDevices(int)':
  src/usb.c:63:9: warning: ignoring return value of 'int system(const char*)' declared with attribute 'warn_unused_result' [8;;https://gcc.gnu.org/onlinedocs/gcc/Warning-Options.html#index-Wunused-result-Wunused-result8;;]
     63 |   system("adb kill-server");
        |   ~~~~~~^~~~~~~~~~~~~~~~~~~
  src/usb.c:67:9: warning: ignoring return value of 'int system(const char*)' declared with attribute 'warn_unused_result' [8;;https://gcc.gnu.org/onlinedocs/gcc/Warning-Options.html#index-Wunused-result-Wunused-result8;;]
     67 |   system("adb kill-server");
        |   ~~~~~~^~~~~~~~~~~~~~~~~~~
  /nix/store/4l1qrgxfy171bngpphp4p9wj7bhrlfn3-binutils-2.34/bin/ld: cannot find -lusbmuxd
  collect2: error: ld returned 1 exit status
  make: *** [Makefile:39: droidcam-cli] Error 1
```

**Comment by suhr** [comment]
It's now merged into nixpkgs.
